def on_up_pressed():
    mySprite.set_velocity(0, -50)
    animation.run_image_animation(mySprite,
        [img("""
                . . . . . . f f f f . . . . . . 
                        . . . . f f e e e e f f . . . . 
                        . . . f e e e f f e e e f . . . 
                        . . f f f f f 2 2 f f f f f . . 
                        . . f f e 2 e 2 2 e 2 e f f . . 
                        . . f e 2 f 2 f f 2 f 2 e f . . 
                        . . f f f 2 2 e e 2 2 f f f . . 
                        . f f e f 2 f e e f 2 f e f f . 
                        . f e e f f e e e e f e e e f . 
                        . . f e e e e e e e e e e f . . 
                        . . . f e e e e e e e e f . . . 
                        . . e 4 f f f f f f f f 4 e . . 
                        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
                        . . . . . f f f f f f . . . . . 
                        . . . . . f f . . f f . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f . . . . . . 
                        . . . . f f e e e e f f . . . . 
                        . . . f e e e f f e e e f . . . 
                        . . . f f f f 2 2 f f f f . . . 
                        . . f f e 2 e 2 2 e 2 e f f . . 
                        . . f e 2 f 2 f f f 2 f e f . . 
                        . . f f f 2 f e e 2 2 f f f . . 
                        . . f e 2 f f e e 2 f e e f . . 
                        . f f e f f e e e f e e e f f . 
                        . f f e e e e e e e e e e f f . 
                        . . . f e e e e e e e e f . . . 
                        . . . e f f f f f f f f 4 e . . 
                        . . . 4 f 2 2 2 2 2 e d d 4 . . 
                        . . . e f f f f f f e e 4 . . . 
                        . . . . f f f . . . . . . . . .
            """),
            img("""
                . . . . . . f f f f . . . . . . 
                        . . . . f f e e e e f f . . . . 
                        . . . f e e e f f e e e f . . . 
                        . . f f f f f 2 2 f f f f f . . 
                        . . f f e 2 e 2 2 e 2 e f f . . 
                        . . f e 2 f 2 f f 2 f 2 e f . . 
                        . . f f f 2 2 e e 2 2 f f f . . 
                        . f f e f 2 f e e f 2 f e f f . 
                        . f e e f f e e e e f e e e f . 
                        . . f e e e e e e e e e e f . . 
                        . . . f e e e e e e e e f . . . 
                        . . e 4 f f f f f f f f 4 e . . 
                        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
                        . . . . . f f f f f f . . . . . 
                        . . . . . f f . . f f . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f . . . . . . 
                        . . . . f f e e e e f f . . . . 
                        . . . f e e e f f e e e f . . . 
                        . . . f f f f 2 2 f f f f . . . 
                        . . f f e 2 e 2 2 e 2 e f f . . 
                        . . f e f 2 f f f 2 f 2 e f . . 
                        . . f f f 2 2 e e f 2 f f f . . 
                        . . f e e f 2 e e f f 2 e f . . 
                        . f f e e e f e e e f f e f f . 
                        . f f e e e e e e e e e e f f . 
                        . . . f e e e e e e e e f . . . 
                        . . e 4 f f f f f f f f e . . . 
                        . . 4 d d e 2 2 2 2 2 f 4 . . . 
                        . . . 4 e e f f f f f f e . . . 
                        . . . . . . . . . f f f . . . .
            """)],
        5,
        True)
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def on_down_released():
    mySprite.set_velocity(0, 0)
    animation.stop_animation(animation.AnimationTypes.ALL, mySprite)
controller.down.on_event(ControllerButtonEvent.RELEASED, on_down_released)

def on_b_released():
    animation.stop_animation(animation.AnimationTypes.ALL, mySprite)
controller.B.on_event(ControllerButtonEvent.RELEASED, on_b_released)

def on_down_pressed():
    mySprite.set_velocity(0, 50)
    animation.run_image_animation(mySprite,
        [img("""
                . . . . . . f f f f . . . . . . 
                        . . . . f f f 2 2 f f f . . . . 
                        . . . f f f 2 2 2 2 f f f . . . 
                        . . f f f e e e e e e f f f . . 
                        . . f f e 2 2 2 2 2 2 e e f . . 
                        . . f e 2 f f f f f f 2 e f . . 
                        . . f f f f e e e e f f f f . . 
                        . f f e f b f 4 4 f b f e f f . 
                        . f e e 4 1 f d d f 1 4 e e f . 
                        . . f e e d d d d d d e e f . . 
                        . . . f e e 4 4 4 4 e e f . . . 
                        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
                        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
                        . . . . . f f f f f f . . . . . 
                        . . . . . f f . . f f . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f . . . . . . 
                        . . . . f f f 2 2 f f f . . . . 
                        . . . f f f 2 2 2 2 f f f . . . 
                        . . f f f e e e e e e f f f . . 
                        . . f f e 2 2 2 2 2 2 e e f . . 
                        . f f e 2 f f f f f f 2 e f f . 
                        . f f f f f e e e e f f f f f . 
                        . . f e f b f 4 4 f b f e f . . 
                        . . f e 4 1 f d d f 1 4 e f . . 
                        . . . f e 4 d d d d 4 e f e . . 
                        . . f e f 2 2 2 2 e d d 4 e . . 
                        . . e 4 f 2 2 2 2 e d d e . . . 
                        . . . . f 4 4 5 5 f e e . . . . 
                        . . . . f f f f f f f . . . . . 
                        . . . . f f f . . . . . . . . .
            """),
            img("""
                . . . . . . f f f f . . . . . . 
                        . . . . f f f 2 2 f f f . . . . 
                        . . . f f f 2 2 2 2 f f f . . . 
                        . . f f f e e e e e e f f f . . 
                        . . f f e 2 2 2 2 2 2 e e f . . 
                        . . f e 2 f f f f f f 2 e f . . 
                        . . f f f f e e e e f f f f . . 
                        . f f e f b f 4 4 f b f e f f . 
                        . f e e 4 1 f d d f 1 4 e e f . 
                        . . f e e d d d d d d e e f . . 
                        . . . f e e 4 4 4 4 e e f . . . 
                        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
                        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
                        . . . . . f f f f f f . . . . . 
                        . . . . . f f . . f f . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f . . . . . . 
                        . . . . f f f 2 2 f f f . . . . 
                        . . . f f f 2 2 2 2 f f f . . . 
                        . . f f f e e e e e e f f f . . 
                        . . f e e 2 2 2 2 2 2 e f f . . 
                        . f f e 2 f f f f f f 2 e f f . 
                        . f f f f f e e e e f f f f f . 
                        . . f e f b f 4 4 f b f e f . . 
                        . . f e 4 1 f d d f 1 4 e f . . 
                        . . e f e 4 d d d d 4 e f . . . 
                        . . e 4 d d e 2 2 2 2 f e f . . 
                        . . . e d d e 2 2 2 2 f 4 e . . 
                        . . . . e e f 5 5 4 4 f . . . . 
                        . . . . . f f f f f f f . . . . 
                        . . . . . . . . . f f f . . . .
            """)],
        5,
        True)
    if controller.B.is_pressed():
        animation.run_image_animation(mySprite,
            [img("""
                    ........................
                                .....ffff...............
                                ...fff22fff.............
                                ..fff2222fff............
                                .fffeeeeeefff...........
                                .ffe222222eef...........
                                .fe2ffffff2ef...........
                                .ffffeeeeffff...........
                                ffefbf44fbfeff..........
                                fee41fddf14eef..........
                                .ffffdddddeef...........
                                fddddf444eef............
                                fbbbbf2222f4e...........
                                fbbbbf2222fd4...........
                                .fccf45544f44...........
                                ..ffffffff..............
                                ....ff..ff..............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                ......ffff..............
                                ....fff22fff............
                                ...fff2222fff...........
                                ..fffeeeeeefff..........
                                ..ffe222222eef..........
                                ..fe2ffffff2ef..........
                                ..ffffeeeeffff..........
                                .ffefbf44fbfeff.........
                                .fee41fddf14eef.........
                                fdfeeddddd4eff..........
                                fbffee444edd4e..........
                                fbf4f2222edde...........
                                fcf.f22cccee............
                                .ff.f44cdc4f............
                                ....fffddcff............
                                .....fddcff.............
                                ....cddc................
                                ....cdc.................
                                ....cc..................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                ........................
                                .......ff...............
                                .....ff22ff.............
                                ...fff2222fff...........
                                ..fff222222fff..........
                                ..fff222222fff..........
                                ..feeeeeeeeeeff.........
                                .ffe22222222eff.........
                                .fffffeeeefffff.........
                                fdfefbf44fbfeff.........
                                fbfe41fddf14ef..........
                                fbffe4dddd4efe..........
                                fcfef22222f4e...........
                                .ff4f44554f4e...........
                                ....ffffffdde...........
                                .....ffffedde...........
                                ..........ee............
                                .........ccc............
                                ........cc1cc...........
                                .........c1c............
                                .........c1c............
                                .........c1c............
                                .........c1c............
                """),
                img("""
                    ......ffff..............
                                ....fff22fff............
                                ...fff2222fff...........
                                ..fffeeeeeefff..........
                                ..ffe222222eef..........
                                ..fe2ffffff2ef..........
                                ..ffffeeeeffff......ccc.
                                .ffefbf44fbfeff....cddc.
                                .ffefbf44fbfeff...cddc..
                                .fee4dddddd4eef.ccddc...
                                fdfeeddddd4eeffecddc....
                                fbffee4444ee4fddccc.....
                                fbf4f222222f1edde.......
                                fcf.f222222f44ee........
                                .ff.f445544f............
                                ....ffffffff............
                                .....ff..ff.............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """)],
            100,
            True)
controller.down.on_event(ControllerButtonEvent.PRESSED, on_down_pressed)

def on_left_released():
    mySprite.set_velocity(0, 0)
    animation.stop_animation(animation.AnimationTypes.ALL, mySprite)
controller.left.on_event(ControllerButtonEvent.RELEASED, on_left_released)

def on_right_released():
    mySprite.set_velocity(0, 0)
    animation.stop_animation(animation.AnimationTypes.ALL, mySprite)
controller.right.on_event(ControllerButtonEvent.RELEASED, on_right_released)

def on_right_pressed():
    mySprite.set_velocity(50, 0)
    animation.run_image_animation(mySprite,
        [img("""
                . . . . . . f f f f f f . . . . 
                        . . . . f f e e e e f 2 f . . . 
                        . . . f f e e e e f 2 2 2 f . . 
                        . . . f e e e f f e e e e f . . 
                        . . . f f f f e e 2 2 2 2 e f . 
                        . . . f e 2 2 2 f f f f e 2 f . 
                        . . f f f f f f f e e e f f f . 
                        . . f f e 4 4 e b f 4 4 e e f . 
                        . . f e e 4 d 4 1 f d d e f . . 
                        . . . f e e e 4 d d d d f . . . 
                        . . . . f f e e 4 4 4 e f . . . 
                        . . . . . 4 d d e 2 2 2 f . . . 
                        . . . . . e d d e 2 2 2 f . . . 
                        . . . . . f e e f 4 5 5 f . . . 
                        . . . . . . f f f f f f . . . . 
                        . . . . . . . f f f . . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f f f . . . . 
                        . . . . f f e e e e f 2 f . . . 
                        . . . f f e e e e f 2 2 2 f . . 
                        . . . f e e e f f e e e e f . . 
                        . . . f f f f e e 2 2 2 2 e f . 
                        . . . f e 2 2 2 f f f f e 2 f . 
                        . . f f f f f f f e e e f f f . 
                        . . f f e 4 4 e b f 4 4 e e f . 
                        . . f e e 4 d 4 1 f d d e f . . 
                        . . . f e e e e e d d d f . . . 
                        . . . . . f 4 d d e 4 e f . . . 
                        . . . . . f e d d e 2 2 f . . . 
                        . . . . f f f e e f 5 5 f f . . 
                        . . . . f f f f f f f f f f . . 
                        . . . . . f f . . . f f f . . .
            """),
            img("""
                . . . . . . f f f f f f . . . . 
                        . . . . f f e e e e f 2 f . . . 
                        . . . f f e e e e f 2 2 2 f . . 
                        . . . f e e e f f e e e e f . . 
                        . . . f f f f e e 2 2 2 2 e f . 
                        . . . f e 2 2 2 f f f f e 2 f . 
                        . . f f f f f f f e e e f f f . 
                        . . f f e 4 4 e b f 4 4 e e f . 
                        . . f e e 4 d 4 1 f d d e f . . 
                        . . . f e e e 4 d d d d f . . . 
                        . . . . f f e e 4 4 4 e f . . . 
                        . . . . . 4 d d e 2 2 2 f . . . 
                        . . . . . e d d e 2 2 2 f . . . 
                        . . . . . f e e f 4 5 5 f . . . 
                        . . . . . . f f f f f f . . . . 
                        . . . . . . . f f f . . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f f f . . . . 
                        . . . . f f e e e e f 2 f . . . 
                        . . . f f e e e e f 2 2 2 f . . 
                        . . . f e e e f f e e e e f . . 
                        . . . f f f f e e 2 2 2 2 e f . 
                        . . . f e 2 2 2 f f f f e 2 f . 
                        . . f f f f f f f e e e f f f . 
                        . . f f e 4 4 e b f 4 4 e e f . 
                        . . f e e 4 d 4 1 f d d e f . . 
                        . . . f e e e 4 d d d d f . . . 
                        . . . . 4 d d e 4 4 4 e f . . . 
                        . . . . e d d e 2 2 2 2 f . . . 
                        . . . . f e e f 4 4 5 5 f f . . 
                        . . . . f f f f f f f f f f . . 
                        . . . . . f f . . . f f f . . .
            """)],
        100,
        True)
    if controller.B.is_pressed():
        animation.run_image_animation(mySprite,
            [img("""
                    ........................
                                ....ffffff..............
                                ..ffeeeef2f.............
                                .ffeeeef222f............
                                .feeeffeeeef...cc.......
                                .ffffee2222ef.cdc.......
                                .fe222ffffe2fcddc.......
                                fffffffeeeffcddc........
                                ffe44ebf44ecddc.........
                                fee4d41fddecdc..........
                                .feee4dddedccc..........
                                ..ffee44e4dde...........
                                ...f222244ee............
                                ...f2222e2f.............
                                ...f444455f.............
                                ....ffffff..............
                                .....fff................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                .......fff..............
                                ....fffff2f.............
                                ..ffeeeee22ff...........
                                .ffeeeeee222ff..........
                                .feeeefffeeeef..........
                                .fffffeee2222ef.........
                                fffe222fffffe2f.........
                                fffffffffeeefff.....cc..
                                fefe44ebbf44eef...ccdc..
                                .fee4d4bbfddef..ccddcc..
                                ..feee4dddddfeecdddc....
                                ...f2222222eeddcdcc.....
                                ...f444445e44ddccc......
                                ...ffffffffeeee.........
                                ...fff...ff.............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    .......ff...............
                                ....ffff2ff.............
                                ..ffeeeef2ff............
                                .ffeeeeef22ff...........
                                .feeeeffeeeef...........
                                .fffffee2222ef..........
                                fffe222ffffe2f..........
                                ffffffffeeefff..........
                                fefe44ebf44eef..........
                                .fee4d4bfddef...........
                                ..feee4dddee.c..........
                                ...f2222eeddeccccccc....
                                ...f444e44ddecddddd.....
                                ...fffffeeee.ccccc......
                                ..ffffffff...c..........
                                ..fff..ff...............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ....ffffff..............
                                ..ffeeeef2f.............
                                .ffeeeef222f............
                                .feeeffeeeef............
                                .ffffee2222ef...........
                                .fe222ffffe2f...........
                                fffffffeeefff...........
                                ffe44ebf44eef...........
                                fee4d41fddef............
                                .feee4ddddf.............
                                ..fdde444ef.............
                                ..fdde22ccc.............
                                ...eef22cdc.............
                                ...f4444cddc............
                                ....fffffcddc...........
                                .....fff..cddc..........
                                ...........cdc..........
                                ............cc..........
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """)],
            100,
            True)
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def on_up_released():
    mySprite.set_velocity(0, 0)
    animation.stop_animation(animation.AnimationTypes.ALL, mySprite)
controller.up.on_event(ControllerButtonEvent.RELEASED, on_up_released)

def on_left_pressed():
    mySprite.set_velocity(-50, 0)
    animation.run_image_animation(mySprite,
        [img("""
                . . . . f f f f f f . . . . . . 
                        . . . f 2 f e e e e f f . . . . 
                        . . f 2 2 2 f e e e e f f . . . 
                        . . f e e e e f f e e e f . . . 
                        . f e 2 2 2 2 e e f f f f . . . 
                        . f 2 e f f f f 2 2 2 e f . . . 
                        . f f f e e e f f f f f f f . . 
                        . f e e 4 4 f b e 4 4 e f f . . 
                        . . f e d d f 1 4 d 4 e e f . . 
                        . . . f d d d d 4 e e e f . . . 
                        . . . f e 4 4 4 e e f f . . . . 
                        . . . f 2 2 2 e d d 4 . . . . . 
                        . . . f 2 2 2 e d d e . . . . . 
                        . . . f 5 5 4 f e e f . . . . . 
                        . . . . f f f f f f . . . . . . 
                        . . . . . . f f f . . . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . f f f f f f . . . . . . 
                        . . . f 2 f e e e e f f . . . . 
                        . . f 2 2 2 f e e e e f f . . . 
                        . . f e e e e f f e e e f . . . 
                        . f e 2 2 2 2 e e f f f f . . . 
                        . f 2 e f f f f 2 2 2 e f . . . 
                        . f f f e e e f f f f f f f . . 
                        . f e e 4 4 f b e 4 4 e f f . . 
                        . . f e d d f 1 4 d 4 e e f . . 
                        . . . f d d d e e e e e f . . . 
                        . . . f e 4 e d d 4 f . . . . . 
                        . . . f 2 2 e d d e f . . . . . 
                        . . f f 5 5 f e e f f f . . . . 
                        . . f f f f f f f f f f . . . . 
                        . . . f f f . . . f f . . . . .
            """),
            img("""
                . . . . f f f f f f . . . . . . 
                        . . . f 2 f e e e e f f . . . . 
                        . . f 2 2 2 f e e e e f f . . . 
                        . . f e e e e f f e e e f . . . 
                        . f e 2 2 2 2 e e f f f f . . . 
                        . f 2 e f f f f 2 2 2 e f . . . 
                        . f f f e e e f f f f f f f . . 
                        . f e e 4 4 f b e 4 4 e f f . . 
                        . . f e d d f 1 4 d 4 e e f . . 
                        . . . f d d d d 4 e e e f . . . 
                        . . . f e 4 4 4 e e f f . . . . 
                        . . . f 2 2 2 e d d 4 . . . . . 
                        . . . f 2 2 2 e d d e . . . . . 
                        . . . f 5 5 4 f e e f . . . . . 
                        . . . . f f f f f f . . . . . . 
                        . . . . . . f f f . . . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . f f f f f f . . . . . . 
                        . . . f 2 f e e e e f f . . . . 
                        . . f 2 2 2 f e e e e f f . . . 
                        . . f e e e e f f e e e f . . . 
                        . f e 2 2 2 2 e e f f f f . . . 
                        . f 2 e f f f f 2 2 2 e f . . . 
                        . f f f e e e f f f f f f f . . 
                        . f e e 4 4 f b e 4 4 e f f . . 
                        . . f e d d f 1 4 d 4 e e f . . 
                        . . . f d d d d 4 e e e f . . . 
                        . . . f e 4 4 4 e d d 4 . . . . 
                        . . . f 2 2 2 2 e d d e . . . . 
                        . . f f 5 5 4 4 f e e f . . . . 
                        . . f f f f f f f f f f . . . . 
                        . . . f f f . . . f f . . . . .
            """)],
        5,
        True)
    if controller.B.is_pressed():
        animation.run_image_animation(mySprite,
            [img("""
                    ..............ffffff....
                                .............f2feeeeff..
                                ............f222feeeeff.
                                .......cc...feeeeffeeef.
                                .......cdc.fe2222eeffff.
                                .......cddcf2effff222ef.
                                ........cddcffeeefffffff
                                .........cddce44fbe44eff
                                ..........cdceddf14d4eef
                                ..........cccdeddd4eeef.
                                ...........edd4e44eeff..
                                ............ee442222f...
                                .............f2e2222f...
                                .............f554444f...
                                ..............ffffff....
                                ................fff.....
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                ..............fff.......
                                .............f2fffff....
                                ...........ff22eeeeeff..
                                ..........ff222eeeeeeff.
                                ..........feeeefffeeeef.
                                .........fe2222eeefffff.
                                .........f2efffff222efff
                                ..cc.....fffeeefffffffff
                                ..cdcc...fee44fbbe44efef
                                ..ccddcc..feddfbb4d4eef.
                                ....cdddceefddddd4eeef..
                                .....ccdcddee2222222f...
                                ......cccdd44e544444f...
                                .........eeeeffffffff...
                                .............ff...fff...
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ...............ff.......
                                .............ff2ffff....
                                ............ff2feeeeff..
                                ...........ff22feeeeeff.
                                ...........feeeeffeeeef.
                                ..........fe2222eefffff.
                                ..........f2effff222efff
                                ..........fffeeeffffffff
                                ..........fee44fbe44efef
                                ...........feddfb4d4eef.
                                ..........c.eeddd4eeef..
                                ....ccccccceddee2222f...
                                .....dddddcedd44e444f...
                                ......ccccc.eeeefffff...
                                ..........c...ffffffff..
                                ...............ff..fff..
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ..............ffffff....
                                .............f2feeeeff..
                                ............f222feeeeff.
                                ............feeeeffeeef.
                                ...........fe2222eeffff.
                                ...........f2effff222ef.
                                ...........fffeeefffffff
                                ...........fee44fbe44eff
                                ............feddf14d4eef
                                .............fdddd4eeef.
                                .............fe444eddf..
                                .............ccc22eddf..
                                .............cdc22fee...
                                ............cddc4444f...
                                ...........cddcfffff....
                                ..........cddc..fff.....
                                ..........cdc...........
                                ..........cc............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """)],
            100,
            True)
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

mySprite: Sprite = None
tiles.set_current_tilemap(tilemap("""
    level1
"""))
mySprite = sprites.create(img("""
        . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . .
    """),
    SpriteKind.player)
scene.camera_follow_sprite(mySprite)
game.show_long_text("Welcome Sir Lancelot to THE KING'S KNIGHT ",
    DialogLayout.BOTTOM)
game.show_long_text("Controls: W= UP S= DOWN D= LEFT A= RIGHT B= ATTACK",
    DialogLayout.BOTTOM)
music.play(music.create_song(hex("""
        005a000408030600001c00010a006400f401640000040000000000000000000000000005000004420000000400012c04000800012c08000c00012a0c001000012910001400012714001800012518001c0001271c002000012920002400012a24002800012c28002c00012c01001c000f05001202c102c201000405002800000064002800031400060200046a0000000400011d04000800011e08000c00011e0c001000012010001400012214001800012018001c0001201c002000011e20002400011d2400280002191b28002c00011b2c003000031e222730003400012034003800011e38003c000224253c004000012740004400012502001c000c960064006d019001000478002c010000640032000000000a0600051e000000040001240c00100001241c002000012024002800011d28002c00011903001c0001dc00690000045e0100040000000000000000000005640001040003310000000400012c04000800012a08000c0001290c00100001271000140001251400180002202418001c00011d1c002000011904001c00100500640000041e000004000000000000000000000000000a0400041e003000340001253400380001253c004000012544004800012548004c00012506001c00010a006400f4016400000400000000000000000000000000000000022a0000000400012904000800012708000c0001250c001000012710001400012914001800012a18001c00012c
    """)),
    music.PlaybackMode.UNTIL_DONE)